sudo: required
dist: trusty
language: node_js
node_js:
  - 'node'
  - '6'
before_script:
  - npm run webpack
  - export TZ=Europe/Rome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
